# Generated by Django 4.2.3 on 2023-07-25 16:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import tutors.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, max_length=2000, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('experience', models.CharField(blank=True, choices=[('<1', 'Менее 1 года'), ('1', 'Более 1 года'), ('2', 'Более 2 лет'), ('3', 'Более 3 лет'), ('5', 'Более 5 лет'), ('10', 'Более 10 лет')], max_length=20, null=True)),
                ('education', models.CharField(blank=True, max_length=255, null=True)),
                ('degree', models.CharField(blank=True, choices=[('st', 'Студент'), ('bch', 'Бакалавр'), ('mg', 'Магистр'), ('phd', 'Кандидат Наук'), ('pf', 'Профессор')], max_length=255, null=True)),
                ('yof', models.IntegerField(blank=True, null=True, validators=[tutors.models.TutorUser.positive_validator])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
                ('files', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='Сертификат')),
                ('salary', models.CharField(blank=True, choices=[(1000, '1000 тнг/час'), (2000, '2000 тнг/час'), (3000, '3000 тнг/час'), (4000, '4000 тнг/час'), (5000, '5000 тнг/час'), (6000, '6000 тнг/час'), (7000, '7000 тнг/час'), (8000, '8000 тнг/час'), (9000, '9000 тнг/час'), (10000, '10000 тнг/час'), (11000, '11000 тнг/час')], max_length=200, null=True, verbose_name='Примерная ставка за час')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео презентацию')),
                ('activate_post', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('avatar', models.URLField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='client_users', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='client_users', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, choices=[(1, '1 star'), (2, '2 star'), (3, '3 star'), (4, '4 star'), (5, '5 star')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to='tutors.clientuser')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tutor', 'client')},
            },
        ),
    ]
