# Generated by Django 4.2.3 on 2023-07-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoruser',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
