# Generated by Django 4.2.3 on 2023-07-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_alter_tutoruser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutoruser',
            name='salary',
            field=models.IntegerField(blank=True, choices=[(1000, '1000 тнг/час'), (2000, '2000 тнг/час'), (3000, '3000 тнг/час'), (4000, '4000 тнг/час'), (5000, '5000 тнг/час'), (6000, '6000 тнг/час'), (7000, '7000 тнг/час'), (8000, '8000 тнг/час'), (9000, '9000 тнг/час'), (10000, '10000 тнг/час'), (11000, '11000 тнг/час')], max_length=200, null=True, verbose_name='Примерная ставка за час'),
        ),
    ]
