# Generated by Django 4.2.3 on 2023-07-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_remove_tutoruser_courses_remove_tutorcourses_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoruser',
            name='courses',
            field=models.ManyToManyField(to='tutors.courses'),
        ),
        migrations.DeleteModel(
            name='TutorCourses',
        ),
    ]
